/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Scanner;
import javax.swing.JOptionPane;
import org.joda.time.Days;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

/**
 *
 * @author johar
 */
public class pReturn extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public pReturn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground3 = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        pnlBookInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtReturnDueDate = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        txtFine = new javax.swing.JTextField();
        txtOverdueBy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPayFine = new javax.swing.JTextField();
        btnPayFine = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        lblBookID = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblBorrowID = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtBookID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtBorrowID = new javax.swing.JTextField();
        lblDate1 = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnCheckBorrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VILB Book Management System");
        setResizable(false);

        panelBackground3.setBackground(new java.awt.Color(163, 193, 173));
        panelBackground3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelTitle.setBackground(new java.awt.Color(0, 33, 71));

        lblTitle1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("VILB");
        lblTitle1.setPreferredSize(new java.awt.Dimension(20, 14));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Return");
        lblTitle.setPreferredSize(new java.awt.Dimension(20, 14));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlButton.setOpaque(false);
        pnlButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(63, 124, 172));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setMaximumSize(new java.awt.Dimension(100, 50));
        btnBack.setMinimumSize(new java.awt.Dimension(100, 50));
        btnBack.setPreferredSize(new java.awt.Dimension(100, 50));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlButton.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnReturn.setBackground(new java.awt.Color(63, 124, 172));
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return");
        btnReturn.setEnabled(false);
        btnReturn.setMaximumSize(new java.awt.Dimension(100, 50));
        btnReturn.setMinimumSize(new java.awt.Dimension(100, 50));
        btnReturn.setPreferredSize(new java.awt.Dimension(100, 50));
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        pnlButton.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        pnlBookInfo.setDoubleBuffered(false);
        pnlBookInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnlBookInfo.setName(""); // NOI18N

        jLabel5.setText("Due Date");

        jLabel6.setText("Return Date");

        jLabel7.setText("Overdue by");

        jLabel8.setText("Fine");

        txtReturnDueDate.setEditable(false);

        txtReturnDate.setEditable(false);

        txtFine.setEditable(false);

        txtOverdueBy.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Return Details");

        jLabel9.setText("Pay Fine");

        txtPayFine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPayFineFocusLost(evt);
            }
        });

        btnPayFine.setBackground(new java.awt.Color(63, 124, 172));
        btnPayFine.setForeground(new java.awt.Color(255, 255, 255));
        btnPayFine.setText("Pay Fine");
        btnPayFine.setEnabled(false);
        btnPayFine.setMaximumSize(new java.awt.Dimension(100, 50));
        btnPayFine.setMinimumSize(new java.awt.Dimension(100, 50));
        btnPayFine.setPreferredSize(new java.awt.Dimension(100, 50));
        btnPayFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayFineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookInfoLayout = new javax.swing.GroupLayout(pnlBookInfo);
        pnlBookInfo.setLayout(pnlBookInfoLayout);
        pnlBookInfoLayout.setHorizontalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(pnlBookInfoLayout.createSequentialGroup()
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(51, 51, 51))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(77, 77, 77)
                        .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReturnDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOverdueBy, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPayFine, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPayFine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlBookInfoLayout.setVerticalGroup(
            pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReturnDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOverdueBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnlBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayFine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBookID.setText("Book ID");

        lblID.setText("Client ID");

        lblBorrowID.setText("Borrow ID");

        lblDate.setText("Borrow Date");

        txtID.setEditable(false);

        txtBookID.setEditable(false);

        txtDate.setEditable(false);

        lblDate1.setText("Due Date");

        txtDueDate.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Borrowing Details");

        btnCheckBorrow.setBackground(new java.awt.Color(63, 124, 172));
        btnCheckBorrow.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckBorrow.setText("Check");
        btnCheckBorrow.setMaximumSize(new java.awt.Dimension(100, 50));
        btnCheckBorrow.setMinimumSize(new java.awt.Dimension(100, 50));
        btnCheckBorrow.setPreferredSize(new java.awt.Dimension(100, 50));
        btnCheckBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBorrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDate1)
                            .addComponent(lblBookID)
                            .addComponent(lblDate)
                            .addComponent(lblID)
                            .addComponent(lblBorrowID))
                        .addGap(34, 34, 34)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBookID, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txtDate)
                            .addComponent(txtDueDate)
                            .addComponent(txtID)
                            .addComponent(txtBorrowID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addComponent(btnCheckBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBorrowID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBorrowID)
                    .addComponent(btnCheckBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookID)
                    .addComponent(txtBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate1)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackground3Layout = new javax.swing.GroupLayout(panelBackground3);
        panelBackground3.setLayout(panelBackground3Layout);
        panelBackground3Layout.setHorizontalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackground3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelBackground3Layout.createSequentialGroup()
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBackground3Layout.setVerticalGroup(
            panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackground3Layout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBackground3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBookInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayFineActionPerformed
       PayFine();
    }//GEN-LAST:event_btnPayFineActionPerformed

    String saveDir, clientID, bookID;
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        saveDir = System.getProperty("user.dir") + "\\src\\DB\\";
        
        try {
            
            borrowID = txtBorrowID.getText();
            clientID = txtID.getText();
            bookID = txtBookID.getText(); 
           
            String obdate = txtDate.getText();
            String oddate = txtDueDate.getText();
            
            Calendar returnDate = Calendar.getInstance();
            SimpleDateFormat datef = new SimpleDateFormat("dd/MM/yyyy");
            String rdate = datef.format(returnDate.getTime());
            
           
                
                File borrow = new File(saveDir + "borrow_t.txt");
                File borrowTemp = new File(saveDir + "borrowTemp_t.txt");

                if (!borrow.exists()){
                    borrowTemp.createNewFile();
                }
             
                borrow.renameTo(borrowTemp);
               
                FileWriter brd = new FileWriter(saveDir + "borrow_t.txt"); 
                
                PrintWriter brdp = new PrintWriter(brd); 
               
                File borrowingtxt = new File(saveDir + "borrowTemp_t.txt");
                
                Scanner inputFile = new Scanner(borrowingtxt);
                
                String[] selectedID;
              
                while (inputFile.hasNext())
                {
                
                    String brEntry = inputFile.nextLine();
               
                    selectedID = brEntry.split(":");
                    
                    if (selectedID[0].equals(borrowID)) {
                        selectedID[5] = rdate;
                        selectedID[6] = "true";
                        if (txtFine.getText().equals("")){
                        selectedID[8] = "0.00";
                        } else {
                        selectedID[8] = txtFine.getText();
                        }
                    }
                    brdp.println(selectedID[0] + ":" +
                                selectedID[1] + ":" +
                                selectedID[2] + ":" +
                                selectedID[3] + ":" +
                                selectedID[4] + ":" +
                                selectedID[5] + ":" +
                                selectedID[6] + ":" +
                                selectedID[7] + ":" +
                                selectedID[8]);

                }
                
                inputFile.close();
                
                borrowingtxt.delete();
            
                brdp.close();
                
                
                JOptionPane.showMessageDialog(null, "Successfully returned!");
                UpdateQuantity();
                ClearText();
                
            } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        pMainMenu mainMenuPage = new pMainMenu();
        mainMenuPage.show();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    
    String dir, borrowID;
    Calendar currentDate = Calendar.getInstance();
    SimpleDateFormat datef = new SimpleDateFormat("dd/MM/yyyy");
    private void btnCheckBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBorrowActionPerformed
        btnReturn.setEnabled(false);
       
        String[] selectedID;
        boolean hasResult = false;
        borrowID = txtBorrowID.getText();

        try {
            dir = System.getProperty("user.dir") + "\\src\\DB\\";
            File clienttxt = new File(dir + "borrow_t.txt");
            Scanner inputFile;
            try {
                inputFile = new Scanner(clienttxt);

                while (inputFile.hasNext())
                {

                    String nextLine = inputFile.nextLine();

                    selectedID = nextLine.split(":");
                    if (selectedID[0].equals(borrowID)){
                        if ("false".equals(selectedID[6])) {
                            hasResult = true;
                            txtBorrowID.setText(selectedID[0]);
                            txtID.setText(selectedID[1]);
                            txtBookID.setText(selectedID[2]);
                            txtDate.setText(selectedID[3]);
                            txtDueDate.setText(selectedID[4]);
                            
                            //Fill in the return details
                            txtReturnDate.setText(datef.format(currentDate.getTime()));
                            txtReturnDueDate.setText(txtDueDate.getText());

                            
                            checkDueDate();
                            
                            //txtNewDueDate.setText("");
                            //CheckRenew();
                        }else {
                            JOptionPane.showMessageDialog(null, "Book has already been returned!", "Book has already been returned!", JOptionPane.ERROR_MESSAGE);
                            ClearText();
                        } 

                    } 
                }
                
                if (!hasResult){
                    JOptionPane.showMessageDialog(null, "No borrow ID found", "No borrow ID found", JOptionPane.ERROR_MESSAGE);
                }
                inputFile.close();

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "No borrow ID found", "No borrow ID found", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e) {
            e.printStackTrace();

            //JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(null, "No Borrow ID found!", "No Borrow ID found!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckBorrowActionPerformed

    private void txtPayFineFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPayFineFocusLost
        if(txtPayFine.getText().contains(":")){
           JOptionPane.showMessageDialog(null, "Invalid symbol ':' used ");
                txtPayFine.setText("");

       } 
    }//GEN-LAST:event_txtPayFineFocusLost
int FineAmount;
    private void checkDueDate(){
         DateTimeFormatter dateFormat = DateTimeFormat.forPattern("dd/MM/yyyy");
           
            LocalDate currentDate = LocalDate.parse(txtReturnDate.getText(),dateFormat );
            
            LocalDate dueDate = LocalDate.parse(txtDueDate.getText(),dateFormat );
            
            //int datediff = Days.daysBetween(currentDate, dueDate).getDays();
            int datediff = Days.daysBetween(dueDate, currentDate).getDays();
            
            if (datediff < 0 ){
                txtOverdueBy.setText("0");
                 btnPayFine.setEnabled(false);
                 btnReturn.setEnabled(true);
            
            } else {
                txtOverdueBy.setText(String.valueOf(datediff));
                 btnPayFine.setEnabled(true);
                 
               FineAmount=datediff*1;
               txtFine.setText(Integer.toString(FineAmount));
            }
    }
    
    String BookID;
    int bookQuantity;
    private void UpdateQuantity(){
    saveDir = System.getProperty("user.dir") + "\\src\\DB\\";
             String[] selectedBookID;
             BookID = txtBookID.getText();
   
            dir = System.getProperty("user.dir") + "\\src\\DB\\";
            File booktxt = new File(dir + "book_t.txt");
            Scanner inputFile;
            try {
                inputFile = new Scanner(booktxt);

                while (inputFile.hasNext())
                {

                    String nextLine = inputFile.nextLine();

                    selectedBookID = nextLine.split(":");
                    if (selectedBookID[0].equals(BookID)){
                        
                        bookQuantity = Integer.parseInt(selectedBookID[5]);
                            
                        }else {
                            //JOptionPane.showMessageDialog(null, "Cannot find the book", "Please ensure that the proper book ID is entered", JOptionPane.ERROR_MESSAGE);
                            ClearText();
                        } 
                    }
                 inputFile.close();
            }catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
            }
            System.out.println("Before " + bookQuantity);
            bookQuantity = bookQuantity + 1;
            System.out.println(bookQuantity);
            
        try {
            
                 
                File book2 = new File(saveDir + "book_t.txt");
                File bookTemp2 = new File(saveDir + "bookTemp_t.txt");

                //if (!bookTemp2.exists()){
                    book2.createNewFile();
               // }
             
                book2.renameTo(bookTemp2);
               
                FileWriter brd2 = new FileWriter(saveDir + "book_t.txt"); 
                
                PrintWriter brdp2 = new PrintWriter(brd2); 
               
                File BookTemptxt = new File(saveDir + "bookTemp_t.txt");
                
                Scanner inputFile2 = new Scanner(BookTemptxt);
                
                String[] selectedID2;
              
                while (inputFile2.hasNext())
                {
                
                    String brEntry = inputFile2.nextLine();
               
                    selectedID2 = brEntry.split(":");
                    
                    if (selectedID2[0].equals(bookID)) {
                        selectedID2[5] = String.valueOf(bookQuantity);
                    }
                    brdp2.println(selectedID2[0] + ":" +
                                selectedID2[1] + ":" +
                                selectedID2[2] + ":" +
                                selectedID2[3] + ":" +
                                selectedID2[4] + ":" +
                                selectedID2[5]); 
                    
              }
                
                inputFile2.close();
                
                BookTemptxt.delete();
            
                brdp2.close();
            } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
            }
    
    }
    
    private void ClearText(){
      txtBorrowID.setText("");
      txtID.setText("");
      txtBookID.setText("");
      txtDate.setText("");
      txtDueDate.setText("");
      txtReturnDate.setText("");
      txtReturnDueDate.setText("");
      txtOverdueBy.setText("");
      txtFine.setText("");
      txtPayFine.setText("");
      btnReturn.setEnabled(false);
    }
    
    int fine, payFine, change;
    private void PayFine(){
        fine = 0;
        payFine = 0;
        change = 0;
        try{
        if (!txtFine.getText().equals("")){
            btnPayFine.setEnabled(true);
            fine = Integer.parseInt(txtFine.getText());
            payFine = Integer.parseInt(txtPayFine.getText());
            
            if (payFine < fine){
                JOptionPane.showMessageDialog(null, " Insufficient amount to pay fine", "Insufficient funds!", JOptionPane.ERROR_MESSAGE);
                txtPayFine.setText("");
            } else{
                change = payFine - fine;
                JOptionPane.showMessageDialog(null, "Payment succesful. The change is " + change);
                btnReturn.setEnabled(true);
            }
        } else {
            btnPayFine.setEnabled(false);
            
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Payment cannot be empty!");
        }
    }
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckBorrow;
    private javax.swing.JButton btnPayFine;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBookID;
    private javax.swing.JLabel lblBorrowID;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel panelBackground3;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JPanel pnlBookInfo;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtBorrowID;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtOverdueBy;
    private javax.swing.JTextField txtPayFine;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtReturnDueDate;
    // End of variables declaration//GEN-END:variables
}
